// Zufallsspiel
Spiel[0]="/anwendungenmath/blackjack/\"><img src=\"/img/blackjack.jpg\" "; 
Spiel[1]="/anwendungenmath/solitaire/\"><img src=\"/img/solitaire.png\" ";
Spiel[2]="/spiele/Sokoban/\"><img src=\"/img/sokoban.png\" ";
Spiel[3]="/spiele/hanoi_mit_grafik/\"><img src=\"/img/hanoi.png\" ";
Spiel[4]="/puzzle/SixteenPuzzle/\"><img src=\"/img/sixteenpuzzle.png\" ";
Spiel[5]="/puzzle/puzzle23/\"><img src=\"/img/puzzle23.png\" ";
Spiel[6]="/anwendungenmath/pento/\"><img src=\"/img/pentominos.png\" ";
Spiel[7]="/puzzle/puzzle14/\"><img src=\"/img/puzzle14.png\" ";
Spiel[8]="/puzzle/puzzle12/\"><img src=\"/img/theseus_klein.png\" ";
Spiel[9]="/puzzle/puzzle20/\"><img src=\"/img/puzzle20.png\" ";
Spiel[10]="/puzzle/puzzle26/\"><img src=\"/puzzle/puzzle26/solut26.jpg\" ";
Spiel[11]="/spiele/euromillions/\"><img src=\"/img/euromillions.png\" ";
Spiel[12]="/spiele/swisslotto/\"><img src=\"/img/swisslotto.png\" ";
Spiel[13]="/spiele/numbers/\"><img src=\"/img/numbers.png\" ";
Spiel[14]="/spiele/sudoku/\"><img src=\"/img/sudoku.png\" ";
Spiel[15]="/spiele/sudoku_x/\"><img src=\"/img/sudokux.png\" ";

// Zufallsknacknüsse
Link[0]="/puzzle/puzzle1.php\"><img src=\"/img/puzzle1.png\" ";
Link[1]="/puzzle/puzzle2.php\"><img src=\"/img/puzzle2.png\" ";
Link[2]="/puzzle/puzzle3.php\"><img src=\"/img/puzzle3.png\" ";
Link[3]="/puzzle/puzzle4.php\"><img src=\"/img/puzzle4.png\" ";
Link[4]="/puzzle/puzzle5.php\"><img src=\"/puzzle/img/puzzle5.png\" ";
Link[5]="/puzzle/puzzle6.php\"><img src=\"/img/puzzle6.png\" ";
Link[6]="/puzzle/puzzle7/\"><img src=\"/img/door.png\" ";
Link[7]="/puzzle/puzzle9.php\"><img src=\"/img/puzzle9.png\" ";
Link[8]="/puzzle/puzzle10.php\"><img src=\"/img/puzzle10.jpg\" ";
Link[9]="/puzzle/puzzle11.php\"><img src=\"/img/puzzle11.jpg\" ";
Link[10]="/puzzle/puzzle15.php\"><img src=\"/img/puzzle15.png\" ";
Link[11]="/puzzle/puzzle17.php\"><img src=\"/puzzle/img/puzzle17.png\" ";
Link[12]="/puzzle/puzzle18.php\"><img src=\"/img/puzzle18.jpg\" ";
Link[13]="/puzzle/puzzle19.php\"><img src=\"/img/puzzle19.jpg\" ";
Link[14]="/puzzle/puzzle21.php\"><img src=\"/img/puzzle21.png\" ";
Link[15]="/puzzle/puzzle22.php\"><img src=\"/img/puzzle22.jpg\" ";
Link[16]="/puzzle/puzzle24.php\"><img src=\"/img/puzzle24.jpg\" ";
Link[17]="/puzzle/puzzle31.php\"><img src=\"/img/puzzle31.png\" ";
Link[18]="/puzzle/puzzle33.php\"><img src=\"/puzzle/img/puzzle33_hund.gif\" ";
Link[19]="/puzzle/puzzle35.php\"><img src=\"/img/puzzle35.jpg\" ";