// Zufallsspiel
var Spiel=new Array();var Link=new Array();
Spiel[0]="<a href=\"anwendungenmath/blackjack/\"><img src=\"/img/blackjack.jpg\">"; 
Spiel[1]="<a href=\"/anwendungenmath/solitaire/\"><img src=\"/img/solitaire.png\">";
Spiel[2]="<a href=\"/spiele/Sokoban/\"><img src=\"/img/sokoban.png\">";
Spiel[3]="<a href=\"/spiele/hanoi_mit_grafik/\"><img src=\"/img/hanoi.png\">";
Spiel[4]="<a href=\"/puzzle/SixteenPuzzle/\"><img src=\"/img/sixteenpuzzle.png\">";
Spiel[5]="<a href=\"/puzzle/puzzle23/\"><img src=\"/img/puzzle23.png\">";
Spiel[6]="<a href=\"/anwendungenmath/pento/\"><img src=\"/img/pentominos.png\">";
Spiel[7]="<a href=\"/puzzle/puzzle14/\"><img src=\"/img/puzzle14.png\">";
Spiel[8]="<a href=\"/puzzle/puzzle12/\"><img src=\"/img/theseus_klein.png\">";
Spiel[9]="<a href=\"/puzzle/puzzle20/\"><img src=\"/img/puzzle20.png\">";
Spiel[10]="<a href=\"/puzzle/puzzle26/\"><img src=\"/puzzle/puzzle26/solut26.jpg\">";
Spiel[11]="<a href=\"/spiele/euromillions/\"><img src=\"/img/euromillions.png\">";
Spiel[12]="<a href=\"/spiele/swisslotto/\"><img src=\"/img/swisslotto.png\">";
Spiel[13]="<a href=\"/spiele/numbers/\"><img src=\"/img/numbers.png\">";
Spiel[14]="<a href=\"/spiele/sudoku/\"><img src=\"/img/sudoku.png\">";
Spiel[15]="<a href=\"/spiele/sudoku_x/\"><img src=\"/img/sudokux.png\">";

// Zufallsknacknüsse
Link[0]="<a href=\"/puzzle/puzzle1.php\"><img src=\"/img/puzzle1.png\">";
Link[1]="<a href=\"/puzzle/puzzle2.php\"><img src=\"/img/puzzle2.png\">";
Link[2]="<a href=\"/puzzle/puzzle3.php\"><img src=\"/img/puzzle3.png\">";
Link[3]="<a href=\"/puzzle/puzzle4.php\"><img src=\"/img/puzzle4.png\">";
Link[4]="<a href=\"/puzzle/puzzle5.php\"><img src=\"/puzzle/img/puzzle5.png\">";
Link[5]="<a href=\"/puzzle/puzzle6.php\"><img src=\"/img/puzzle6.png\">";
Link[6]="<a href=\"/puzzle/puzzle7/\"><img src=\"/img/door.png\">";
Link[7]="<a href=\"/puzzle/puzzle9.php\"><img src=\"/img/puzzle9.png\">";
Link[8]="<a href=\"/puzzle/puzzle10.php\"><img src=\"/img/puzzle10.jpg\">";
Link[9]="<a href=\"/puzzle/puzzle11.php\"><img src=\"/img/puzzle11.jpg\">";
Link[10]="<a href=\"/puzzle/puzzle15.php\"><img src=\"/img/puzzle15.png\">";
Link[11]="<a href=\"/puzzle/puzzle17.php\"><img src=\"/puzzle/img/puzzle17.png\">";
Link[12]="<a href=\"/puzzle/puzzle18.php\"><img src=\"/img/puzzle18.jpg\">";
Link[13]="<a href=\"/puzzle/puzzle19.php\"><img src=\"/img/puzzle19.jpg\">";
Link[14]="<a href=\"/puzzle/puzzle21.php\"><img src=\"/img/puzzle21.png\">";
Link[15]="<a href=\"/puzzle/puzzle22.php\"><img src=\"/img/puzzle22.jpg\">";
Link[16]="<a href=\"/puzzle/puzzle24.php\"><img src=\"/img/puzzle24.jpg\">";
Link[17]="<a href=\"/puzzle/puzzle31.php\"><img src=\"/img/puzzle31.png\">";
Link[18]="<a href=\"/puzzle/puzzle33.php\"><img src=\"/puzzle/img/puzzle33_hund.gif\">";
Link[19]="<a href=\"/puzzle/puzzle35.php\"><img src=\"/img/puzzle35.jpg\">";